import express from 'express';
import path from 'path';
import routes from './routes/routes';
const app = express();
app.use(express.urlencoded({ extended: true }));
app.use(express.static(path.join(__dirname, 'public')));
app.set('view engine', 'ejs');
app.set('views', path.join(__dirname, 'views'));
app.use(routes);
app.listen(3000);
