import express from 'express';
import mongoose from 'mongoose';
mongoose.set('strictQuery', false);
import ClassRoutes from './routes/StudentsRoutes/RoutesClass';
import StudentsRoutes from './routes/StudentsRoutes/RoutesStudents';
import ManagerRoutes from './routes/ManagerRoutes/RoutesManager';
import RoutesExits from './routes/ExitsRoutes/RoutesExits';
import OrganizationRoutes from './routes/OrganizationRoutes/RoutesOrganization'
import { config } from 'dotenv';
config();
mongoose.connect(process.env.connectionString);
const app = express();
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use(ClassRoutes);
app.use(ManagerRoutes);
app.use(RoutesExits);
app.use(StudentsRoutes);
app.use(OrganizationRoutes);
app.listen(3000);
